name: publish to server #action名称
on:
  push:
    branches: [main]
  # pull_request:
  #   branches: [master]

jobs:
  deploy_job:
    runs-on: ubuntu-latest #运行环境
    name: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        # check out the repository
        with:
          always-auth: true
          node-version: 16
          cache: 'yarn'
      - name: Checkout
        uses: actions/checkout@v2 #这里使用了github官方提供的action,checkout项目到虚拟机上

      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn build

      # 利用action把build好的文件上传到服务器/var/www/react-app路径下,需要确认此目录已在服务端创建
      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'root' #ssh user name
          server: '${{ secrets.SERVERIP }}' #引用之前创建好的secret
          ssh_private_key: ${{ secrets.SERVERSSH }} #引用之前创建好的secret
          local_path: './build/*' # 对应我们项目build的文件夹路径
          remote_path: 'work/webapps/front-test/'
